// config.js
const fs =
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkFQU1FOYVE4UEFGZUJvOFNvK2EyYkM1WWF1NGtYUkJMR3ZXQjR4OUtYQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU2JCR0hhQzcxeEs3WFd0ZUVlc2pESUZTM3F6a0lobHhLR0Z2VHZnNE0yYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNT1E4YmtUaURkdmlzWDFwcDhMcUt2TVJoMkhvZm1UWEZOR29laWVIOFhjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjMUJNU3NVa0xwYnJjSkw5OTMyS0ZSVzkzZFJEcDdZanVWWElEeit0RXdBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im9QQVZidUpxOElnZjkrSkMrUzBlVjVVN29yM0dQdEVVcDVtS2FkektERkU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IllkUmx1UnJ0Z3NMaDFMR3g2dzdBT2NnSHlsY3huWWtLTkM4Zk9PUTZvVk09In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0d0Y1paV3pMNllIYjhIZkdPcGIvNGdwYlZaN0FIcUlOTFg1T05jTFNGcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTWNxa2QwRkxNa2F1YXJKdzhIWFBqUUgvL3FvZTd5aFlqWkNGT29ia2FSVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitsaUp3SHZiMkpUMXB4bXBZS3QrRjlSZlp0VUYybTdOWnZEakdwV0wwWkNmOEhCTmNjQ2lENTNyU0Z1Yytycml4L05ZL0NZS2cxeTRyYzVqY25GL0JnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE2LCJhZHZTZWNyZXRLZXkiOiJGeklZcTlWdUE5azRzMDYyM0J3NTcwNVBUY3ZsM0NxZnd3eEZpU0VnWGN3PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJqRkdtOUtOdFJXaVkxaG5GNzQ4UHBRIiwicGhvbmVJZCI6ImI3YmY4YjFmLWExMGYtNDVjZS1hYjg5LThkYmVjNGVjZjZjNiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0UU5nMnZWR2YzZ2xwSVBXclA0U1NCMjBvcUk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicW03eERKRTRSVCt3UGJ3aEE1RVNlNWZhS1ljPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Ikg1TEg3UUIxIiwibWUiOnsiaWQiOiI5NDc2MjQ5ODUxOTo5OEBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTHZnNnZRREVKTHpoN1VHR0FZZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5Ijoiak5JSmNYRWNWU3V0SGZaK2JxVHl4OUlUVGU3RjE0OUpQUnZrVU9LZlZXdz0iLCJhY2NvdW50U2lnbmF0dXJlIjoic2JZNEEwUFEwdXd6bVJiZWxQOWZBTEsraThJTTQ4elVqV1dyYVBqWmlzOVR2YlE2TEJTaVc1S2NXT01JOU1RUVMrRlpvdkFLMnNvaU9xNUtOOW5tRHc9PSIsImRldmljZVNpZ25hdHVyZSI6Im5CUllVdzRKNmRlMG5FRXlMUEs2U212bW8wQ3h3NU1nc2NNT3ppcFVJL01tN1k2bXZ4Z1R2amd6Q2VEUHVuRE1aWVU1SW1RU3ZzOVFpREpsbkRSVEJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTQ3NjI0OTg1MTk6OThAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWXpTQ1hGeEhGVXJyUjMyZm02azhzZlNFMDN1eGRlUFNUMGI1RkRpbjFWcyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMTg5MTIzMCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFIWk8ifQ==",
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "rush",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "94761011111",
  GEMINI_KEY: process.env.GEMINI_KEY || "",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
