// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU5tZGRETCs1aUNIeUpDbEVQZnNIOG9WNkFYcTRHc2lPWTl6a3hGSGwwbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWGZUdC9tL0ZDUGg5QzUvbURpTjNaRU9XNG0wWjRKYVBySk03bHV3a2FRVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpTW1LcmlPejh3ODEwbk91M3U0ZUJnZEFpWTBCVVVxdlk0bnlPbDUyeldFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBUjRiTEE2SUx6ZGh2QUFxMndpeUhreGdSaFlyNG9BR0d2RHZDcGM4UHo0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFDelZ3UGZZcTRFQmRqd0IzZ1BrK2tZbDdJaGpoUnYxa3pPcXlHVWd2VUE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InV3V29CV3EvMnhkUFFocFZjTm1aRng1WDdqU0ZxeTA4ZjFPemtQYU9rU2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUw1N0FmQ29ZNFdVamJHZzd1Y2dLUHdCcms4UCs1Z2tmQnNWZU8zTVBGZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiblZhWGxyMDNwUmlpWVlsM2tRaTJpYkxYWFB0RVNWVzIwMVlWK1ZsdzhpQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikl5SzBoTlg0VUJrWGNDVURpcm5FNG1odnZwRkYxcUJzb0VINXlVZlNPNk5GRzBURjBYQjFUVG10bHdpQkJMU0ljSUduQUZuUHZmc28vM2xwb1pCbWl3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NywiYWR2U2VjcmV0S2V5IjoiL0dqNmNUTDZOazlNSDJwR3c1SHJEdFVrUE1KM0JibzV1YlNNN3V5UUw3Zz0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiT1pydGxGdl9SZXFucDc3c3FQNTZjdyIsInBob25lSWQiOiIzYTQ5NjEyNC05NTdjLTRlNzEtYWU3NC03ZTc2ZjBlZWMxYjkiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiemJHSU43T1gwZGlyeEE3L3VZNUZROHdTWUFBPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImhPTm15cENpem1yRnY2VjY5a0UrZC9laTQ0az0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJFOUJYM0VBSCIsIm1lIjp7ImlkIjoiOTQ3MTEwMjQ0NjM6MTdAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0tTcWtyWUJFTENIZzdVR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlY0TkowRTk0WUVPRFVrMU9yL2RzN2lVckx5OEFsemdVRDNncFI4b1RjaTA9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkdzQm9JTG0vcE5nRmc4VERLVXVNQW00YWhlaUJ3blR1c2kxQ2dRYWhrTHRKZjZZcENhaWVodGR1eU81VWtrRGZvUnE5TlVnTS9TTTJMUVQ0cVYzUURBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJVRk02elNkVlF0RkJydGFGNUlTaXdVQWhFa3BXSDZpa2tHRGpYSHo2WCswRTJPQkhidFl6VERpL2RLMklmbXpaQkZRdU1mRHNyUkFyaC92bEwzcFBpZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0NzExMDI0NDYzOjE3QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlZlRFNkQlBlR0JEZzFKTlRxLzNiTzRsS3k4dkFKYzRGQTk0S1VmS0UzSXQifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjE4MTE5MDEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSHB5In0=",
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "rush",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "94761011111",
  GEMINI_KEY: process.env.GEMINI_KEY || "",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
